config/routes.rb
Rails.application.routes.draw do
  # Might be more intuitive to name this "home#index"
  # and create a home controller and views/home/index.html.erb file
  # (This route isn't really an index page for users)
  root to: "users#index"

  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:username", to: "users#show", as: "user"
  get "/users/:username/edit", to: "users#edit", as: "edit_user"
  patch "/users/:username", to: "users#update"

  # Highly recommend nesting routes using resources:
  # resources :cities do
  #   resources :posts do
  #     resources :comments
  #   end
  # end

  # This would create routes like the following:
  # /cities/:city_id
  # /cities/:city_id/posts
  # /cities/:city_id/posts/:post_id
  # /cities/:city_id/posts/:post_id/comments
  # /cities/:city_id/posts/:post_id/comments/:comment_id

  # This is recommended ^, because 
  # 1) It's intuitive (cities have posts, posts have comments) 
  # 2) You have all necessary params for requests in your URL (when you are, say, creating a new post, you have the city_id in the URL)
  # 3) It's short / easy to write
  # 4) It's widely considered best practice (mainly for the above reasons)

  get "/posts/:id", to: "posts#show", as: "post"
  get "/posts/:id/edit", to: "posts#edit", as: "edit_post"
  patch "/posts/:id", to: "posts#update"
  delete "posts/:id", to: "posts#destroy"

  get "posts/:id/comments/new", to: "comments#new", as: "new_comment"
  post "posts/:id/comments", to: "comments#create"
  get "posts/:id/comments/:comment_id/edit", to: "comments#edit", as: "edit_comment"
  patch "posts/:id/comments/:comment_id", to: "comments#update", as: "update_comment"
  delete "posts/:id/comments/:comment_id", to: "comments#destroy"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  get "cities/:cityname", to: "cities#show", as: "city"
  get "cities/:cityname/posts/new", to: "posts#new", as: "new_post"
  post "cities/:cityname/posts", to: "posts#create", as: "create_post"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  
  # Never have lines go off the page – just add newlines and indent 
  has_attached_file :avatar, 
    styles: { medium: "300x300>", thumb: "100x100>" }, 
    default_url: "http://gazettereview.com/wp-content/uploads/2016/06/myspce-tom-photo-300x300.jpg"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :name, :current_city, presence: true
  validates :name, uniqueness: true
  
  has_secure_password

  # Format files to be more readable.
  # Use your best judgment – in this file, I separated code by functionality
  # (associations, validations, etc.)

  def self.confirm(params)
      @user = User.find_by({name: params[:name]})
      @user ? @user.authenticate(params[:password]) : false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_user, only: [:edit, :update]

  def index
    # This gets the first 5 Users, in order of ascending id
    @users = User.find(:all, :order => "id asc", :limit => 5)
  end

  def new
    if current_user
      flash[:error] = "You cannot sign up while you are logged in."
      redirect_to current_user and return
    end
    @user = User.new
  end

  def create
    if current_user
      flash[:error] = "You cannot sign up while you are logged in."
      redirect_to current_user and return
    end
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_path(@user.name)
    else
      flash[:error] = @user.errors.full_messages.join(" ")
      render new_user_path
    end
  end

  def show
    @user = User.find_by(name: params[:username])
    if @user == nil
      flash[:error] = "User does not exist"
      redirect_to root_path
    end

  end

  def edit
    @user = User.find_by(name: params[:username])
  end

  def update
    @user = User.find_by(name: params[:username])
    if @user.update(user_params)
      redirect_to user_path(@user.name)
    else
      flash[:error] = @user.errors.full_messages.join(" ")
      redirect_to user_path(@user.name)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :current_city, :password, :avatar)
  end

  def verify_user
    if current_user[:name].to_s != params[:username].to_s
      flash[:notice] = "No permission to edit other user information"
      redirect_to user_path
    end
  end
end

# Great use of _path helpers in all controllers 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-4">
  </div>
  <!-- Indentation and offset classes ^ -->
  <%= form_for @user, url: "/users/#{@user.name}" do |f| %>
      <div class="form-group row">
        <%= f.label :name, class:"col-form-label col-sm-5" %>
        <%= f.text_field :name, class: "form-control col-sm-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :current_city, class:"col-form-label col-sm-5" %>
        <%= f.text_field :current_city, class: "form-control col-sm-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :avatar, class:"col-form-label col-sm-5" %>
        <%= f.file_field :avatar, as: :file, class: "form-control col-sm-7" %>
      </div>
      <div class="form-group row">
        <div class="col-sm-5">
        </div>
        <%= f.submit "Save", class:"btn btn-primary" %>&nbsp&nbsp
        <%= link_to "Cancel", user_path(current_user.name), class:"btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= image_tag "http://vagabondrva.com/wp-content/uploads/2016/03/vagabond-logo-final-500.jpg", class:"img-fluid"%>
<h2 class="center-link">Meet some of our fellow college students!</h2>
<div class="row margin-photo-background">
  <!--<div class="col-sm-1"></div>-->
  <% @users.each do |user| %>
    <div class="col-md-2 root-bottom-margin">
      <%= link_to user_path(user.name), class: "image-link" do %>
        <%= image_tag user.avatar.url, class: "root-photos img-fluid img-responsive" %>
      <%end%>
      <div class="center-link"><%=user.name%></div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
    </div>
    <%= form_for @user do |f| %>
        <div class="form-group row">
            <%= f.label :name, class:"col-form-label col-sm-5" %>
            <%= f.text_field :name, :maxlength => 20, class: "form-control col-sm-7" %>
        </div>
        <div class="form-group row">
            <%= f.label :current_city, class:"col-form-label col-sm-5" %>
            <%= f.text_field :current_city, :maxlength => 20, class: "form-control col-sm-7" %>
        </div>
        <div class="form-group row">
            <%= f.label :password, class:"col-form-label col-sm-5" %>
            <%= f.password_field :password, class: "form-control col-sm-7" %>
        </div>
      <%= f.file_field :avatar, as: :file %>
      <div class="form-group row">
        <div class="col-sm-5">
        </div>
          <%= f.submit "Sign Up", class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="show-left-side col-sm-3">
    <h1><%=@user.name%></h1>
    <%= image_tag @user.avatar.url, class: "show-image"%>
    <p><strong>Join Date: </strong><%=@user.created_at.strftime("%F")%></p>
    <p><strong>Current City: </strong><%=@user.current_city%></p>
    <p><strong>Comments left: </strong><%=@user.comments.length%></p>
    <% City.all.each do |city| %>
      <% if @user.posts.where(city: city).length > 0 %>
        <p><strong><%= link_to city.name, city_path(city.name) %>: </strong><%=@user.posts.where(city: city).length%> posts</p>
      <% end %>
    <% end %>
    <% if current_user && current_user.name.to_s == params[:username].to_s%>
      <%= link_to "Edit User", edit_user_path(@user.name), class:"btn btn-primary back-color"%>
    <% end %>
  </div>

  <div class="show-right-side col-sm-9">
    <ul>
      <% @user.posts.each do |post| %>
      <div class="row">
        <div class="col-sm-10">
					<div class="card card-inverse card-primary mb-3">
           <div class="card-block">
               <h3><%= link_to post.title, post_path(post)%></h3>
               <p>Posted <%=time_ago_in_words(post.created_at)%> ago&nbsp;&nbsp;&nbsp;&nbsp;City: <%= link_to post.city.name, city_path(post.city.name)%></p>
               <p><%= truncate(post.content,length: 300) {link_to "See more", post}%></p>
           </div>
          </div>

        </div>
        <% if current_user && current_user.name.to_s == params[:username].to_s%>
        <div class="col-sm-2">
          <%= link_to "Edit Post", edit_post_path(post), class:"btn btn-primary back-color" %><br>
          <%= link_to "Delete Post", post, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary back-color" %>
        </div>
        <% end %>
      </div>
    <% end %>
    </ul>
  </div>

</div>