config/routes.rb
Rails.application.routes.draw do
  # Might be more intuitive to name this "home#index"
  # and create a home controller and views/home/index.html.erb file
  # (This route isn't really an index page for users)
  root to: "users#index"

  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:username", to: "users#show", as: "user"
  get "/users/:username/edit", to: "users#edit", as: "edit_user"
  patch "/users/:username", to: "users#update"

  # Highly recommend nesting routes using resources:
  # resources :cities do
  #   resources :posts do
  #     resources :comments
  #   end
  # end

  # This would create routes like the following:
  # /cities/:city_id
  # /cities/:city_id/posts
  # /cities/:city_id/posts/:post_id
  # /cities/:city_id/posts/:post_id/comments
  # /cities/:city_id/posts/:post_id/comments/:comment_id

  # This is recommended ^, because 
  # 1) It's intuitive (cities have posts, posts have comments) 
  # 2) You have all necessary params for requests in your URL (when you are, say, creating a new post, you have the city_id in the URL)
  # 3) It's short / easy to write
  # 4) It's widely considered best practice (mainly for the above reasons)

  get "/posts/:id", to: "posts#show", as: "post"
  get "/posts/:id/edit", to: "posts#edit", as: "edit_post"
  patch "/posts/:id", to: "posts#update"
  delete "posts/:id", to: "posts#destroy"

  get "posts/:id/comments/new", to: "comments#new", as: "new_comment"
  post "posts/:id/comments", to: "comments#create"
  get "posts/:id/comments/:comment_id/edit", to: "comments#edit", as: "edit_comment"
  patch "posts/:id/comments/:comment_id", to: "comments#update", as: "update_comment"
  delete "posts/:id/comments/:comment_id", to: "comments#destroy"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  get "cities/:cityname", to: "cities#show", as: "city"
  get "cities/:cityname/posts/new", to: "posts#new", as: "new_post"
  post "cities/:cityname/posts", to: "posts#create", as: "create_post"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_many :comments

  validates :title, :content, presence: true
  validates :title, length: {maximum: 200}

  default_scope { order("created_at DESC") }
  # Format files to be more readable.
  # Use your best judgment – in this file, I separated code by functionality
  # (associations, validations, etc.)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :verify_logged_in, except: [:show]
	before_action :find_and_verify_user, only: [:edit, :update, :destroy]

  def new
  	@post = Post.new
  	@city = City.find_by(name: params[:cityname])
  end

  def create
  	@post = Post.new post_params
  	@post.user = current_user
  	@post.city = City.find_by(name: params[:cityname])
  	if @post.save
  		redirect_to @post
  	else
  		flash[:error] = @post.errors.full_messages.join(" ")
  		redirect_to new_post_path
  	end
  end

  def show
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
  end

  def edit
  end

  def update
  	if @post.update post_params
  		redirect_to @post
  	else
  		flash[:error] = @post.errors.full_messages.join(" ")
  		redirect_to @post
  	end
  end

  def destroy
  	@post.delete
  	redirect_to user_path(current_user.name)
  end

  private
  
  def post_params
  	params.require(:post).permit(:title,:content,:user,:city)
  end

  def verify_logged_in
  	if !current_user
  		flash[:error] = "You must be logged in to create or modify posts"
  		redirect_to City.find_by(name: params[:cityname]) and return
  	end
  end

  def find_and_verify_user
  	@post = Post.find(params[:id])
  	if current_user != @post.user
  		flash[:error] = "You don't have permission to modify other users' posts"
  		redirect_to @post and return
  	end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-2">
  </div>
  <!-- USE BOOTSTRAP OFFSET CLASSES, INSTEAD OF EMPTY DIVS ^ -->
  <%= form_for @post do |f| %>
      <div class="form-group row">
        <%= f.label :title, class:"col-form-label col-sm-3" %>
        <%= f.text_field :title, class: "form-control col-sm-9" %>
      </div>
      <div class="form-group row">
        <%= f.label :content, class:"col-form-label col-sm-3" %>
        <%= f.text_area :content, class: "form-control col-sm-9", size: "60x15"%>
      </div>

    <div class="form-group row">
      <div class="col-sm-5">
      </div>
        <%= f.submit "Submit", class:"btn btn-primary" %> &nbsp&nbsp
        <%= link_to "Cancel", user_path(@post.user_id), class:"btn btn-primary btn-md" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-2">
  </div>
  <!-- indentation!! -->
  <%= form_for @post, url: create_post_path(@city.name), method: "post" do |f| %>
      <div class="form-group row">
        <%= f.label :title, class:"col-form-label col-sm-3" %>
        <%= f.text_field :title, class: "form-control col-sm-9" %>
      </div>
      <div class="form-group row">
        <%= f.label :content, class:"col-form-label col-sm-3" %>
        <%= f.text_area :content, class: "form-control col-sm-9", size: "60x15" %>
      </div>

    <div class="form-group row">
      <div class="col-sm-5">
      </div>
        <%= f.submit "Submit", class:"btn btn-primary" %> &nbsp&nbsp
        <%= link_to "Cancel", city_path(@city.name), class:"btn btn-primary btn-md" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="row">

  <!-- indentation!! -->
  <div class="show-left-side col-sm-3">
    <h1><%=@post.user.name%></h1>
    <%= link_to user_path(@post.user.name) do %>
      <%= image_tag @user.avatar.url, class: "show-image"%>
    <%end%>
  </div>

  <div class="show-right-side col-sm-9">
    <div class="row">
      <div class="col-sm-9">
        <h4><strong><%= link_to @post.city.name, city_path(@post.city.name) %></strong></h4>
        <h3><%= @post.title %></h3>
        <p class="overflow-posts"><%= @post.content %></p>
        <div>
          <!-- The indentation below this line makes me really sad -->
<p><%= @post.comments.length%> comments</p>
</div>
<% @post.comments.each do |comment| %>
<div class="row">
<div class="col-sm-10">
<p class="overflow-posts">
  <%= link_to user_path(comment.user.name), class: "image-link" do %>
    <%= image_tag comment.user.avatar.url, class: "comment-image"%>
  <%end%>
  <strong><%=link_to comment.user.name, user_path(comment.user.name) %>: </strong><%= comment.content %></p>
</div>
<div class="col-sm-2">
<% if current_user && comment.user == current_user %>
<%= link_to "Edit", "/posts/#{@post.id}/comments/#{comment.id}/edit", class:"btn btn-primary btn-sm back-color" %>
<%= link_to "Delete", "/posts/#{@post.id}/comments/#{comment.id}", method: :delete, class:"btn btn-primary btn-sm back-color" %>
<% end %>
</div>

</div>
<% end %>
<% if current_user %>
<%= link_to "Add comment", new_comment_path(@post) %>
<% end %>
      </div>
      <div class="col-sm-3">
        <% if current_user && @post.user == current_user %>
            <%= link_to "Edit Post", edit_post_path(@post), class:"btn btn-primary back-color"%>
            <%= link_to "Delete Post", @post, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary back-color"%>
        <% end %>
      </div>
    </div>
  </div>


</div>