config/routes.rb
Rails.application.routes.draw do
  # Might be more intuitive to name this "home#index"
  # and create a home controller and views/home/index.html.erb file
  # (This route isn't really an index page for users)
  root to: "users#index"

  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:username", to: "users#show", as: "user"
  get "/users/:username/edit", to: "users#edit", as: "edit_user"
  patch "/users/:username", to: "users#update"

  # Highly recommend nesting routes using resources:
  # resources :cities do
  #   resources :posts do
  #     resources :comments
  #   end
  # end

  # This would create routes like the following:
  # /cities/:city_id
  # /cities/:city_id/posts
  # /cities/:city_id/posts/:post_id
  # /cities/:city_id/posts/:post_id/comments
  # /cities/:city_id/posts/:post_id/comments/:comment_id

  # This is recommended ^, because 
  # 1) It's intuitive (cities have posts, posts have comments) 
  # 2) You have all necessary params for requests in your URL (when you are, say, creating a new post, you have the city_id in the URL)
  # 3) It's short / easy to write
  # 4) It's widely considered best practice (mainly for the above reasons)

  get "/posts/:id", to: "posts#show", as: "post"
  get "/posts/:id/edit", to: "posts#edit", as: "edit_post"
  patch "/posts/:id", to: "posts#update"
  delete "posts/:id", to: "posts#destroy"

  get "posts/:id/comments/new", to: "comments#new", as: "new_comment"
  post "posts/:id/comments", to: "comments#create"
  get "posts/:id/comments/:comment_id/edit", to: "comments#edit", as: "edit_comment"
  patch "posts/:id/comments/:comment_id", to: "comments#update", as: "update_comment"
  delete "posts/:id/comments/:comment_id", to: "comments#destroy"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

  get "cities/:cityname", to: "cities#show", as: "city"
  get "cities/:cityname/posts/new", to: "posts#new", as: "new_post"
  post "cities/:cityname/posts", to: "posts#create", as: "create_post"
end

app/models/city.rb
class City < ApplicationRecord
	has_many :posts
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def show
		@city = City.find_by(name: params[:cityname])
		@posts = @city.posts.page(params[:page]).per(10)
	end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/show.html.erb
<!-- BREAK UP HTML TO BE MORE READABLE (BY MAJOR SECTIONS OF PAGE) -->

<div class="row">
	<h1 class="col-sm-10"><%= @city.name %></h1>
	<% if current_user %>
		<%= link_to "New Post", new_post_path(@city.name), class: "col-sm-2 btn btn-primary back-color" %>
	<% end %>
</div>

<%= image_tag @city.photo, class: "img-fluid" %>

<br>

<% @posts.each do |post| %>
	<!-- FORMAT PROPERLY! INDENTATION IS ESPECIALLY IMPORTANT IN HTML; HARD TO DEBUG OTHERWISE -->
	<div class="card card-inverse card-primary mb-3">
	 	<div class="card-block">
			<h3><%= link_to post.title, post_path(post)%></h3>
			<p>
				<strong>
					Author: <%= link_to post.user.name, user_path(post.user.name)%>&nbsp;<%= link_to user_path(post.user.name), class: "image-link" do %>
	    			<%= image_tag post.user.avatar.url, class: "comment-image"%>
	  			<%end%>&nbsp;&nbsp;&nbsp;
	  		</strong>Posted <%=time_ago_in_words(post.created_at)%> ago
	  	</p>
			<p><%= truncate(post.content,length: 300) {link_to "See more", post}%></p>
	 </div>
	</div>
<% end %>

<%= paginate @posts, theme: 'twitter-bootstrap-4'%>